### ISSUE TITLE
moveActiveWindowToDesktop does not working with NOT english locale

### ISSUE THREAD

**Issue by pragmaton** [jpginc/windows10DesktopManager#10]
I have Win10 with russian localisation. So your trick wih M hotkey does not work, since "Move to" menu item is on russian and have no "m" letter inside.

**Comment by pragmaton** [comment]
I did try to fix this problem. My patch working for me so far. But I'm not sure if it's correct way to fix problem. What do you think?

**Comment by jpginc** [comment]
That wont work as different computers have different context menus. On my work computer I only have two menu items ('move to' and close). I don't know why the context menu is different so I don't think we can assume that `{down 3}` will work on every computer. Any other ideas?

**Comment by pragmaton** [comment]
> different computers have different context menus. On my work computer I only have two menu items

Yep, this is why I was not sure if my solution is correct. Personally, I just switched to english UI. 

As  I see 2 possbile general solutions:

1) Use winapi for this. Unfortunately, I have no idea how to do this :) May be source fhttps://github.com/Eun/MoveToDesktop can help.

2) Not perfect. Just explain the situation in documentation and let people configure keys sequence by themselves?

**Comment by jpginc** [comment]
Eun's MoveToDesktop looks interesting. It looks like he injects some code into the windows so that it can move itself using the dll functions used in virtualDesktopManager.ahk. I can't figure exactly how it injects the code though

**Comment by jpginc** [comment]
https://msdn.microsoft.com/en-us/library/windows/desktop/ms644990(v=vs.85).aspx looks interesting. I'll look into whether we can use this maybe tonight

**Comment by jpginc** [comment]
this might help us to inject ahk code into another process https://autohotkey.com/board/topic/85304-solvedget-other-processs-working-dir/page-3#entry544650

**Comment by jpginc** [comment]
asking for help here https://autohotkey.com/boards/viewtopic.php?f=5&t=18813

**Comment by jpginc** [comment]
I've made some progress in 5a270d67700b26d2ed95395c1651cc95a5c7795d, run Test.ahk and windows key + a sends the active window to desktop 4.

**Comment by jpginc** [comment]
if we go with the dll approach we will need two instances of the script running, one in 32bit and one in 64. http://stackoverflow.com/questions/8575736/setwindowshook-to-support-both-32-bit-and-64-bit-application

**Comment by jpginc** [comment]
I've merged the new dll approach and it appears to be working quite well. let me know if there are any issues
