### ISSUE TITLE
hey, any idea why the move to desktop does not work. Great work otherwise, it was badly needed. Cheers,Jonathan

### ISSUE THREAD

**Issue by darkzbaron** [jpginc/windows10DesktopManager#13]

**Comment by jpginc** [comment]
are there any error popups? 
What version of windows are you using (ie are you using a preview version)?

**Comment by darkzbaron** [comment]
Hey Thanks for your message and Apologies for the delayed answer. Yes I'm on a preview. I have got another computer running a non preview though. Do you think it's related? Thanks so much. I am looking forward to hear back from you. Kind Regards,

 Jonathan

From: jpginc
Sent: Tuesday, 12 July 2016 04:49
To: jpginc/windows10DesktopManager
Reply To: jpginc/windows10DesktopManager
Cc: darkzbaron; Author
Subject: Re: [jpginc/windows10DesktopManager] hey, any idea why the move to desktop does not work. Great work otherwise, it was badly needed. Cheers,Jonathan (#13)

are there any error popups?
What version of windows are you using (ie are you using a preview version)?

---

**Comment by darkzbaron** [comment]
Version 1607 (OS Build 14372.0)
sorry replied too fast, it simply does nothing. other shortcuts work though

**Comment by jpginc** [comment]
I'm thinking that the IVirtualDesktopManagerInternal interface has been removed from the preview version of windows (I found this issue https://github.com/Grabacr07/VirtualDesktop/issues/9). I assume that if it's removed from the preview then that means it will be removed from windows 10 all together at some point in the not too distant future.

The internal virtual desktop stuff isn't officially supported by windows so I guess we should remove its use from the project, or at least have a fallback. We are using the internal interfaces in the dll (https://github.com/jpginc/MoveToDesktop/blob/master/Hook/hook.cpp) to get the GUID of the destination desktop. I think we were extracting the GUID from the Registry a while ago so we could change the interface of the dll to accept a GUID and a HWND and remove the references to the internal interface.

**Comment by darkzbaron** [comment]
ok, thanks so much. It's a shame it's a badly needed function. Anyway thanks for pûtting together such a great piece.

**Comment by jpginc** [comment]
Thanks I'm glad you like it. I don't have time to fix it right now but I should be able to get around to it towards the end of next week

**Comment by jpginc** [comment]
@darkzbaron I've changed the dll to not use the IVirtualDesktopManagerInternal interface. Can you checkout this commit e27e3bccc487d6035073dc55a9715b9b9e889f4e and confirm that it's working on the preview version of windows?

**Comment by jpginc** [comment]
This should be resolved in master from this commit f3e171e2d189e50cee8644ac5ddd9b7aee906dd6
