### ISSUE TITLE
move window to desktop doesn't work on command shell

### ISSUE THREAD

**Issue by adamjudson** [jpginc/windows10DesktopManager#14]
Windows 10 Home 64 bit

When current window is a command shell (cmd.exe) move window to next/previous desktop and move window to desktop # do not work.  Command shell does not move, desktop does not switch.  Works correctly on all other application windows.

Move to next/previous desktop and move to desktop # work correctly with all windows, including cmd.exe.

I see the autohotkey icon appear briefly in the task bar, so I suspect the key strokes are being picked up.  Maybe an issue with getting the window handle?

**Comment by jpginc** [comment]
I'm getting the same behaviour on Windows 10 Pro 64bit. I'll try to look into it late next week

**Comment by jpginc** [comment]
according to this page we can't hook into cmd.exe http://microsoft.public.win32.programmer.tools.narkive.com/X4AmQ75v/setwindowshookex-failure-with-console-applications i might be able to default to the other method of moving windows for cmd.exe...

**Comment by jpginc** [comment]
I've added an exception to console windows in this commit 060a0f2e0ca77922599aefc48336b34971e0fbb6

have a go, if it works for you i'll merge it into main

**Comment by adamjudson** [comment]
Change seems to work correctly for command shell - though there's a lot of screen flickering.

Recently (today) updated to Windows 10 Home version 1607.  Now move window to desktop doesn't work on non-cmd windows with either new version of this file, or existing version.   Switching desktops continues to work correctly.

Let me know what addition information I can provide.

**Comment by jpginc** [comment]
the screen flickering in this instance is required unfortunately.

As for the update, this is probably linked to #13 . I have already implemented a fix for this so will pull it into the main branch.

**Comment by jpginc** [comment]
This should have been fixed in the master branch from commit 060a0f2e0ca77922599aefc48336b34971e0fbb6
