### ISSUE TITLE
Can't Use Ctrl + Win + Shift Modifier Keys

### ISSUE THREAD

**Issue by saulback** [jpginc/windows10DesktopManager#16]
Maybe I'm understanding the hotkeys wrong, but I believe the below should allow me to do a Ctrl+Win+Shift + right/left to move the windows either right or left. 

```
.setMoveWindowToNextDesktop("^+# & >")
.setMoveWindowToPreviousDesktop("^+# & <")
```

Unfortunately I get an error saying "^+#" is not a valid key name.

**Comment by jpginc** [comment]
I can't tell if you want to use the left/right arrows or the less than/greater than keys

In either case It's just a syntax error. Because Ctrl, Win, Shift are modifiers there is no need to use the &. it should be 

```
.setMoveWindowToNextDesktop("^+#right")
.setMoveWindowToPreviousDesktop("^+#left")
```

or

```
.setMoveWindowToNextDesktop("^+#.")
.setMoveWindowToPreviousDesktop("^+#,")
```
