### ISSUE TITLE
Feature: Add desktop-specific wallpapers

### ISSUE THREAD

**Issue by ghost** [jpginc/windows10DesktopManager#17]
I was studying this code to find the command for getting the current desktop's ID and couldn't figure it out (d'oh!). I ended up lifting a method from another code and wrote a background-changing standalone at https://github.com/noido/ahk-change_windows_virtualDestop_background

**Comment by jpginc** [comment]
To get the current desktop id you can use the VirtualDesktopManagerClass' getWindowDesktopId function. You pass it a HWND of a window on that desktop. I found the registry approach not to work if there are multiple sessions. I see that @noido has found a way to find the current session in his script (getSessionId function).

**Comment by jpginc** [comment]
I don't think I'll add the feature of desktop specific wallpapers but if enough people really want it then they can re-open the issue
