### ISSUE TITLE
win+tab view not working correctly

### ISSUE THREAD

**Issue by shiro** [jpginc/windows10DesktopManager#22]
The desktops view (win+tab) doesn't behave as expected, for instance after switching desktops, if there is at least 1 window on the destination desktop, the desktop view is closed (probably because of some alt+tab being triggered).

**Comment by jpginc** [comment]
Do you mean that if you 

1. enter the desktops view by pressing windows + tab
2. Change desktops using this script (eg capslock + 4)

That the desktops view is closed after changing to desktop 4?

**Comment by shiro** [comment]
Affirmative, haven't tried any other commands besides simply switching left/right though.

**Comment by jpginc** [comment]
That was by design, the code that is doing it is in the doPostGoToDesktop function here: https://github.com/jpginc/windows10DesktopManager/blob/master/desktopChanger.ahk#L69 

If you can give me a scenario when this behavior would be annoying I would be happy to change it.

**Comment by shiro** [comment]
win+tab gives a good overview of all virtual desktops and windows on them. It makes it easy to quickly cycle through virtual desktops without actually focusing on one.

For instance, maybe I had many desktops with many windows open, and I just wanted to see what windows are on desktop n without actually focusing it (and not getting an overview of windows on it).

**Comment by jpginc** [comment]
seems reasonable. updated with this commit 67ec0293053862bb508e0659876b94c8d97deb06
