### ISSUE TITLE
Follow to desktop not working

### ISSUE THREAD

**Issue by damagu** [jpginc/windows10DesktopManager#26]
I'm using windows10DesktopManager on my old laptop with the following modified lines in windows10.ahk:

```
globalDesktopManager.setGoToDesktop("<^<#")	; LCtrl+LWin+[1-9]	- Go to desktop number [1-9] 
    .setMoveWindowToDesktop("<^<!")    		; LCtrl+LAlt+[1-9]	- Move active window & go to desktop number [1-9] 
    .setMoveWindowToNextDesktop("<^<!right")	; LCtrl+LAlt+Right	- Move active window to next desktop 
    .setMoveWindowToPreviousDesktop("<^<!left")	; LCtrl+LAlt+Left	- Move active window to previous desktop
    .setCloseDesktop("<^<#<+x")			; LCtrl+LWin+LShift+X	- Close current desktop
	.setNewDesktop("<^<#<+n")		; LCtrl+LWin+LShift+N	- Create new desktop
    .followToDesktopAfterMovingWindow(true)
```
This uses Ctrl + Alt + [Left/Right] to move windows to previous/next desktop and it follows the window when it moves. 

However, for some reason, when I tried to use this same set up on my new laptop, it won't follow the window when the window moves.

Both laptops are running 64bit Windows 10 and both have windows10.ahk modified in the same way. As far as I'm aware everything else is the same. 

I tried forcing windowMover.ahk to follow on move by changing:
```followToNewDesktop := false``` to ```followToNewDesktop := true``` 
and 
```follow := false``` to ```follow := true``` 
wherever they appear, but that didn't help so I reverted back to the original.

Extra info: I've also tried using different combos of keys. E.g. 
- the original ```"Capslock & s"```, 
- ```"LCtrl & LShift & Left"```, also written as ```"<^<+left"```, 
- ```"LCtrl & LShift & LAlt & Left"``` also written as ```"<^<+<!left"```,
None of these work either. 
And, in the original script, you had semi-colon, tilde, space ```;~ ``` in front of  ```.followToDesktopAfterMovingWindow(true)```... I know semi-colon is used to comment lines out but I'm not sure what the tilde does so, when I uncommented the line, I tried running the script with tilde included and with it removed. Neither version worked.

Can you suggest what might be wrong with my set up and/or how to fix it?

Thanks

**Comment by jpginc** [comment]
very strange. Can you add a msgbox in the `_followWindow` function in windowMover.ahk. Maybe like this

```
_followWindow(hwnd)
	{
msgbox, "follow window is getting called!"
		if(this.followToNewDesktop)
		{
msgbox, "and i'm trying to follow to the next desktop"
			this._deActivateActiveWindow()
			WinActivate, % "ahk_id " hwnd
		}
		return this
	}
```
also, why is there no return in the _deActivateActiveWindow function. It's been a while since I've played with autohotkey so maybe it's fine... Try  adding a return anyway.

```
_deActivateActiveWindow()
	{
		Gui, new
		Gui, Show
		Gui, destroy
return this
	}
```

**Comment by damagu** [comment]
Okay. I grabbed a fresh copy of the original files and made the changes you suggested as well as uncommenting the ```.followToDesktopAfterMovingWindow(true)``` line in windows10.ahk. 

I then ran the script and used the ```Capslock + s``` hotkey to call ( as set in the ```.setMoveWindowToNextDesktop("Capslock & s")``` line) which caused the active window to move and the "follow window is getting called!" message to appear (I think it happened in that order but it was too fast for me to be sure about the order). 
After I dismissed the first message, the second message "and i'm trying to follow to the next desktop" appeared. 
Unfortunately, (at least as far I can tell) at no point does the active desktop change.

I don't know whether you need it but here's the output data:
- [Lines most recently executed](https://pastebin.com/DrKRVvMu) 
- [Variables and their contents](https://pastebin.com/VdLGdBfL)
- [Hotkeys and their methods](https://pastebin.com/ZLYqm3MD) 
- [Key history and script info](https://pastebin.com/0J1KUVke).

I should also point out that the hotkeys for GoToNextDesktop and GoToPreviousDesktop are working just fine.

In case it helps at all, while I was waiting to hear back on my first post, I created my own version of the script where I copied: 
- moveActiveWindowToNextDesktop
to create these two variations: 
- moveActiveWindowToNextDesktop**NoFollow** - with follow essentially hard coded to false. 
- moveActiveWindowToNextDesktop**AndFollow** - with follow essentially hard coded to true. 

I did the same with moveActiveWindowToPreviousDesktop. This was partly in attempt to test further but also because -- if I ever manage to get the "AndFollow" option working -- I'd prefer to be able to assign separate hotkeys to the "AndFollow" and "NoFollow" options because then I can use "NoFollow" AND/OR "AndFollow" rather than "NoFollow" XOR "AndFollow". 

Even though the changes seemed to work (no obvious errors anyway), the "AndFollow" hotkeys still don't trigger a follow to occur after the move effectively making them do the same thing as the "NoFollow" versions.

**Comment by damagu** [comment]
I've now also tried running the scripts on a MS Surface and I'm having the same problem there... I can move windows to previous/next desktop but I cannot get it to follow on move.

**Comment by jpgincus** [comment]
thanks for the info. Lets try using the function that is working then. For now change the moveActiveWindowToDesktop function in windowMover.ahk to look like this: 

```
moveActiveWindowToDesktop(targetDesktop, follow := false)
	{
		activeHwnd := WinExist("A")
		if(this.dllWindowMover.isAvailable()) 
		{
			this.dllWindowMover.moveActiveWindowToDesktop(targetDesktop)
		} else 
		{
			currentDesktop := this.desktopMapper.getDesktopNumber()
			if(currentDesktop == targetDesktop) 
			{
				return this
			}
			numberOfTabsNeededToSelectActiveMonitor := this.monitorMapper.getRequiredTabCount(WinActive("A"))
			numberOfDownsNeededToSelectDesktop := this.getNumberOfDownsNeededToSelectDesktop(targetDesktop, currentDesktop)
			
			openMultitaskingViewFrame()
			send("{tab " numberOfTabsNeededToSelectActiveMonitor "}")
			send("{Appskey}m{Down " numberOfDownsNeededToSelectDesktop "}{Enter}")
			closeMultitaskingViewFrame()
		}
		
		tmp := new JPGIncDesktopChangerClass()
                tmp.goToDesktop(targetDesktop)
		
		return	this
	}
```

If that works i'll update it properly when i have a few minutes

**Comment by damagu** [comment]
Okay. That works! At first, when I went to change the hotkeys it stopped working but I think it was because I was making the changes in the wrong version of the script because now I've got it working with the keys I want it using. 

Cheers

**Comment by damagu** [comment]
If you are changing things, it'd be great if you could allow assigning separate keys for:
- move window (no follow)
AND
- move window and follow
... so we can use both instead of one or the other.

I managed to do this in my own version as mentioned above but I don't really know what I'm doing and I'd prefer if it was built in to the original. 

Cheers

**Comment by jpginc** [comment]
I've updated the script to fix your original bug (following the window not working). i don't have a windows computer to test on tat the moment...could you test that it's working? :-). 

I'll think about how to change things for the "and follow" "no follow" idea.

**Comment by raycekar** [comment]
One thing I noticed as I had to do this workaround as well is the moved window loses focus, so you cant chain together a move of that window unless you click on it to move it again.  Maybe having it autofocus that last window would be good?

**Comment by jpgincus** [comment]
To clairfy, when you move a window and follow it to the new desktop, the window that you moved doesn't have focus? That is probably why we had the `_deActivateActiveWindow()` function. Can you try this:

change line 46 in windowMover.ahk from:
`		this._followWindow(targetDesktop)`
to:
`		this._followWindow(targetDesktop, activeHwnd)`

and change the `_followWindow` function to be:

```
        _followWindow(targetDesktop, activeHwnd)
	{
		if(this.followToNewDesktop)
		{
		        ; Activate a new window so that we can activate the old one
		        Gui, new 
                        Gui, Show
			this._desktopChanger.goToDesktop(targetDesktop)
			WinActivate, % "ahk_id " activeHwnd
                        Gui, Destroy
		}
		return this
	}
```

**Comment by raycekar** [comment]
yes, I am referring to when the window is moved, and then the screen follows to the next desktop, the moved window is no longer the active window.

I reverted all changes, then updated line 46 along with updated _followWindow function, and it now is back where it will move the window but will not follow

**Comment by damagu** [comment]
@raycekar I have also noticed this. It prevents me from moving a window across multiple desktops too since after each move the window deactivates which means it can't be the target for the next move until its activated again.

I've also noticed a couple of other things:

1) on some occasions a window moves to the next/previous desktop but there's no follow. I'll need to test more to work out if there's any pattern to it.

And 

2) sometimes an app window doesn't move to another desktop. The desktop switches but the window gets left behind. When that has happened I've switched back to the desktop with the window I was trying to move and I've tried to move it again but it still hasn't worked and I end up having to hit Windows+Tab and manually drag-&-drop the window onto the desired desktop. Again, I'll have to do some testing to see if there's any pattern to it.

@jpginc... As far as you're aware, are there any situations, app types or app-window types which might cause problems for the movewindow and/or movewindowandfollow functions? I dont know if all app windows can be modal or modeless like vba userforms and dialogue boxes can be but it has occurred to me that it might be something like that preventing a window from being moved.

**Comment by damagu** [comment]
> I've updated the script to fix your original bug (following the window not working). i don't have a windows computer to test on tat the moment...could you test that it's working? :-).
> 
> I'll think about how to change things for the "and follow" "no follow" idea.

My apologies I thought I had replied to this months ago. Yes it is working. However, I am using my modified version where I've taken setMoveWindowToNextDesktop & setMoveWindowToPreviousDesktop and used the code to create 4 alternative functions:
- setMoveWindowToNextDesktopNoFollow 
- setMoveWindowToPrevDesktopNoFollow
- setMoveWindowToNextDesktopAndFollow 
- setMoveWindowToPrevDesktopAndFollow 

which are have the boolean value coded into them so instead of assigning a global value for followToDesktopAfterMovingWindow I can assign hotkeys to the follow and nofollow functions separately and use both.

**Comment by jpginc** [comment]
sorry i've been slow on this, been busy with other stuff. so this issue:

> when the window is moved, and then the screen follows to the next desktop, the moved window is no longer the active window.

was a little annoying. After the window is moved, it loses focus and `winactivate` calls are ignored.  I've put a hack in that creates a new window, activates that new window and then activates the moved window. it takes half a second for that to happen though which is a little annoying but the best i can do for now.

@damagu 

> are there any situations, app types or app-window types which might cause problems for the movewindow and/or movewindowandfollow functions? 

The only ones i'm aware of is the cmd prompt window as it doesn't allow you to do dll injection (which is how we are moving windows). is it always the same program that wont switch?

**Comment by jpgincus** [comment]
I made some more updates that i think will make moving desktops and windows less glitchy so i think this issue can now be closed. let me know if it's still an issue or just open a new bug.
