### ISSUE TITLE
How to add this script in the autostart programs?

### ISSUE THREAD

**Issue by codeforcesmeme** [jpginc/windows10DesktopManager#28]
I tried compiling the script but the dlls and other ahk scripts don't get into the final binary, also tried dumping the whole thing in the start up folder but the closest I got was after only having the `windows10.ahk` in the startup folder and move other files into the  %appdata% root and import them dynamically with `%A_AppData%/...` but this only had a problem with this line because during the actual boot/startup the `dll/dllCaller.ahk` is somehow not read from the same directory instead it tries to get the reference/import from some folder in system32 folder.

https://github.com/jpginc/windows10DesktopManager/blob/72758ef6bc9e7e2a56af1a91d84240a8c714f0c1/dllWindowMover.ahk#L23

**Comment by aloneunix** [comment]
Create scheduled task as shown here: https://github.com/Eun/MoveToDesktop/blob/master/help/scheduled-tasks.md.
In the action creation step specify following paths:
- Program/script: C:\path\to\AutoHotkeyU64.exe
- Add arguments: C:\path\to\windows10DesktopManager\windows10.ahk
- Start in:  C:\path\to\windows10DesktopManager\

When done, you can run task manually.

**Comment by jpginc** [comment]
@aloneunix 's solution is a good one. You could also put a .bat file in the startup folder with something like this.

```
cd C:\path\to\windows10DesktopManager\ && windows10.ahk
```
