### ISSUE TITLE
send window to next/previous desktop feature

### ISSUE THREAD

**Issue by shiro** [jpginc/windows10DesktopManager#8]
Being able to move a window to the next/previous desktop without knowing its number would prove rather helpful.

**Comment by jpginc** [comment]
What do you mean "without knowing its number"?

**Comment by shiro** [comment]
Simply sending it to the right/left desktop relative to the current one, instead of "sending it to desktop n".

**Comment by jpginc** [comment]
I've added two functions to the `JPGIncDesktopManagerClass`
`setMoveWindowToNextDesktop` and `setMoveWindowToPreviousDesktop` that can do this
